### ISSUE TITLE
Failed to find provider info for com.huawei.hms

### ISSUE THREAD

**Issue by lechao** [HMS-Core/hms-3d-modeling-demo#14]
E/ActivityThread: Failed to find provider info for com.huawei.hms
W/dynamic-api_DynamicModule: 3142-3142|null|com.huawei.hms.feature.dynamic.DynamicModule|getRemoteVersion|80|Query remote module:huawei_module_modeling3d_motioncapture exception:com.huawei.hms.feature.dynamic.DynamicModule$g: failed to Query remote version.
E/AbstractInitializer: huawei_module_modeling3d_motioncapture -> No need to switch because the context of the dynamic module is null or the context of full sdk
E/AbstractInitializer: huawei_module_modeling3d_motioncapture -> The context of the dynamic module belongs to LOCAL
D/ImageSkeletonImpl: Initialize
E/SkeletonDetectionJNI: loadLibrary failed. UnsatisfiedLinkError e: java.lang.UnsatisfiedLinkError: dlopen failed: library "libnative-lib.so" not found
E/.hms.modeling3: No implementation found for int com.huawei.hms.motioncapturesdk.SkeletonDetectionJNI.createInstance(android.content.res.AssetManager, java.lang.String, java.lang.String, java.lang.String, java.lang.String) (tried Java_com_huawei_hms_motioncapturesdk_SkeletonDetectionJNI_createInstance and Java_com_huawei_hms_motioncapturesdk_SkeletonDetectionJNI_createInstance__Landroid_content_res_AssetManager_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.huawei.hms.modeling3d, PID: 3142
    java.lang.UnsatisfiedLinkError: No implementation found for int com.huawei.hms.motioncapturesdk.SkeletonDetectionJNI.createInstance(android.content.res.AssetManager, java.lang.String, java.lang.String, java.lang.String, java.lang.String) (tried Java_com_huawei_hms_motioncapturesdk_SkeletonDetectionJNI_createInstance and Java_com_huawei_hms_motioncapturesdk_SkeletonDetectionJNI_createInstance__Landroid_content_res_AssetManager_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2)
        at com.huawei.hms.motioncapturesdk.SkeletonDetectionJNI.createInstance(Native Method)
        at com.huawei.hms.motioncapturesdk.a.initialize(ImageSkeletonImpl.java:12)
        at com.huawei.hms.motioncapturesdk.t.b.a(RemoteOnDeviceSkeleton.java:14)
        at com.huawei.hms.motioncapturesdk.Modeling3dMotionCaptureEngine.create(Modeling3dMotionCaptureEngine.java:13)
        at com.huawei.hms.motioncapturesdk.Modeling3dMotionCaptureEngineFactory.getMotionCaptureEngine(Modeling3dMotionCaptureEngineFactory.java:1)
        at com.huawei.hms.modeling3d.utils.skeleton.LocalSkeletonProcessor.<init>(LocalSkeletonProcessor.java:65)
        at com.huawei.hms.modeling3d.ui.activity.SelectSourceVideoActivity.onCreate(SelectSourceVideoActivity.java:103)
        at android.app.Activity.performCreate(Activity.java:7994)
        at android.app.Activity.performCreate(Activity.java:7978)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by Xuejiao-Shi** [comment]
It is recommended that you re-integrate Huawei libraries. The error may be caused by something missing. If the error persists, pls let me know how to reproduce the problem.
